= JBake plugin for Gradle

This plugin allows rendering a site using http://www.jbake.org[JBake] directly from http://www.gradle.org[Gradle].

== Usage

[source,groovy]
----
buildscript {
  repositories {
      jcenter()
      maven {
          url "http://xbib.org/repository"
      }
  }

  dependencies {
    classpath 'org.xbib.gradle.plugin:jbake-gradle-plugin:1.0'
  }
}

apply plugin: 'org.xbib.gradle.jbake'
----

This will add a `jbake` task to your build, which will search for a standard http://www.jbake.org[JBake] source tree in
`src/jbake` and generate content into `$buildDir/jbake` (typically `build/jbake`).

== Configuration
=== Plugin configuration

The default input and output directories can be changed using the `jbake` configuration block:

[source,groovy]
----
jbake {
    srcDirName  = 'jbake-sources'
    destDirName = 'output'
}
----
The generated output can then be found at `$buildDir/output`.

The Version could be changed too:

[source,groovy]
----
jbake {
    version  = '2.3.0'
}
----

The default is 2.3.2.

=== Render Engine configuration

Jbake uses three engines. The library versions could be changed too:

[source,groovy]
----
jbake {

    pegdownVersion = '1.4.2'
    freemarkerVersion = '2.3.19'
    asciidoctorJavaIntegrationVersion = '0.1.4'
    asciidoctorjVersion = '1.5.1'
}
----

Notice the `asciidoctorJavaIntegrationVersion` and `asciidoctorjVersion`. Since Version 2.3.1 jbake has changed
to the asciidoctorj library.

This plugin handles this change internally. If you use a Version > 2.3.0 of jbake, the dependency switch to the new one.

=== JBake configuration
There are several options to configure http://www.jbake.org[JBake]. One is to have the regular `jbake.properties` file
into the source directory. The other is to use the plugin configuration block:

[source,groovy]
----
jbake {
   configuration['template.post.file'] = 'mypost.ftl'
}
----

